### ISSUE TITLE
Help: Unable to use Pangolin's name resolution

### ISSUE THREAD

**Issue by davidclaeysquinones** [stevenlovegrove/Pangolin#980]
In order to explain my problem I need to give some context about what I'm trying to achieve.
I have multiple Docker hosts, some on a local network, other on VPS instances.

I want to deploy one single management interface for all of them behind Pangolin.
Right  now I'm trying to deploy [Komodo](https://github.com/moghtech/komodo), but this could be really any other tool.

On my Pangolin server (VPS 2), my docker compose yaml looks like this (I'll be redacting it in order to not get too long-winded) :

```
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    .......
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    restart: unless-stopped
    .......
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    restart: unless-stopped
    ..........
    networks:
      - default
      - pangolin
    .......................
  periphery-vps-2:
    image: ghcr.io/moghtech/komodo-periphery:latest
    restart: unless-stopped
    ..........
networks:
  default: {}
  pangolin:
    external: true
```

The core service is the Komodo application, and it needs access to the Docker agent called periphery.
This works just fine, no issues there.

However I have another server (VPS 1), where I have newt client setup.
There I want to setup the periphery and connect it to my other machine.
My yaml looks like this :

```
services:
  periphery-vps-1:
    image: ghcr.io/moghtech/komodo-periphery:latest
    restart: unless-stopped
   ..............
    networks:
      pangolin-client_default:
networks:
  pangolin-client_default:
    external: true
```
_pangolin-client_default_ is the name of the network of the newt  client.

I expected that the agent would be reachable through _periphery-vps-1_ on VPS 2.
I've already looked into adding aliases, to no avail. 
Is what I'm trying to do even possible and if so how should I go about it ?

Note:
The reason that I want to do things this way is in order to isolate internal services (Komodo database) from everything else.
Also, publicly exposing the Docker agents over the internet would be cumbersome and a massive security risk.
